---
- name: Install dependencies
  xbps:
    pkg:
      - git
      - libffi-devel
      - python-devel
      - python-virtualenv
      - uwsgi
      - uwsgi-python
      - mit-krb5-client
    state: present

- name: Configure firewall for account_site
  copy:
    src: account_site.rules
    dest: /etc/iptables.d/account_site.rules
    owner: root
    group: root
    mode: 0640
  notify:
  - iptables

- name: Create the account-services group
  group:
    name: cv_account
    state: present
    system: yes

- name: Create the account-servicess user
  user:
    name: cv_account
    group: cv_account
    state: present
    system: yes

- name: Create account services directory
  file:
    path: /opt/account-services
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Install account services
  git:
    repo: https://github.com/collegiumv/cv_account.git
    dest: /opt/account-services
    version: 897b6ae
    umask: "0022"
  notify:
    - account-services

- name: Install account services pip dependencies
  pip:
    requirements: "/opt/account-services/requirements.txt"
    umask: '0022'
    virtualenv: "/opt/account-services/venv"
    virtualenv_python: "python2"

- name: Create config directory
  file:
    path: /opt/account-services/config
    owner: root
    group: cv_account
    mode: 0750
    state: directory 
  notify:
    - account-services

- name: Create the log directory
  file:
    path: /opt/account-services/log
    state: directory
    owner: cv_account
    group: root
    mode: 0700
  notify:
    - account-services

- name: Copy secrets
  copy:
    src: secret/account_{{ item }}
    dest: /opt/account-services/config/{{ item }}
    owner: root
    group: cv_account
    mode: 0640
  with_items:
    - access.list
    - words.txt
    - blacklist.txt
  notify:
    - account-services

- name: Copy keytab
  copy:
    src: secret/krb5_account-services-admin.keytab
    dest: /opt/account-services/krb5.keytab
    owner: cv_account
    group: cv_account
    mode: 0400
  notify:
    - account-services

- name: Copy Configuration
  template:
    src: settings.json
    dest: /opt/account-services/config/settings.json
    owner: root
    group: cv_account
    mode: 0640
  notify:
    - account-services

- name: Configure account-services service (1/3)
  file:
    path: /etc/sv/account-services
    state: directory
    owner: root
    group: root
    mode: 0755
  notify:
    - account-services

- name: Configure account-services service (2/3)
  copy:
    src: run
    dest: /etc/sv/account-services/run
    owner: root
    group: root
    mode: 0755
  notify:
    - account-services

- name: Configure account-services service (3/3)
  runit:
    name: account-services
    enabled: yes
    state: started

- name: Add account sites
  copy:
    src: "{{ item }}.conf"
    dest: /etc/nginx/sites-available/{{ item }}.conf
    owner: root
    group: root
    mode: 0644
  with_items:
    - account
    - accounts
  notify:
    - nginx

- name: Enable account sites
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    owner: root
    group: root
    state: link 
  with_items:
    - account
    - accounts
  notify:
    - nginx
