---
- name: Create the reposync group
  group:
    name: reposync
    state: present

- name: Create the reposync User
  user:
    name: reposync
    state: present

- name: Allow nginx to see the mirror
  user:
    name: nginx
    group: reposync

- name: Install rsync
  xbps:
    pkg: rsync
    state: present

- name: Create mirror directory
  file:
    path: /mnt/mirror/void
    state: directory
    owner: reposync
    group: reposync
    mode: 0755

- name: Create secret directory
  file:
    path: /etc/void-mirror
    owner: reposync
    group: reposync
    mode: 0750
    state: directory

- name: Install sync secret
  copy:
    src: secret/void_mirror.sync
    dest: /etc/void-mirror/sync.secret
    owner: reposync
    group: reposync
    mode: 0600

- name: Install sync service (1/2)
  file:
    path: /etc/sv/void-mirror
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install sync service (2/2)
  copy:
    src: void-mirror.run
    dest: /etc/sv/void-mirror/run
    owner: root
    group: root
    mode: 0755

- name: Enable sync service
  runit:
    name: void-mirror
    enabled: yes
    state: started

- name: Install nginx config
  copy:
    src: void-mirror.conf
    dest: /etc/nginx/sites-available/void-mirror.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable nginx config
  file:
    src: ../sites-available/void-mirror.conf
    dest: /etc/nginx/sites-enabled/void-mirror.conf
    state: link
  notify:
    - nginx

- name: Install iptables rules
  copy:
    src: void-mirror.rules
    dest: /etc/iptables.d/void-mirror.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
