---
- name: Install dependencies
  xbps:
    pkg:
      - git
    state: present

- name: Create site directory
  file:
    path: /var/www/welcome
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install site contents
  git:
    repo: https://github.com/collegiumv/cv_welcome.git
    dest: /var/www/welcome
    version: 813480e
    umask: "0022"

- name: Correct Site Permissions
  file:
    path: /var/www/welcome
    state: directory
    recurse: true
    owner: root
    group: root
    mode: og+rX

- name: Add Welcome site
  copy:
    src: welcome.conf
    dest: /etc/nginx/sites-available/welcome.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable Welcome site
  file:
    src: ../sites-available/welcome.conf
    dest: /etc/nginx/sites-enabled/welcome.conf
    state: link
  notify:
    - nginx
